### ISSUE TITLE
Thanks / Which file? / bitmapy font?

### ISSUE THREAD

**Issue by ghostlyghastly** [Sasabmeg/fallout-classic-dialog-font#1]
THANK YOU! I was sick and tired of janky "jh_fallout" being claimed as "the" text font of fallout 1/2. This one also isn't the real ticket: https://passion.tumblr.com/post/70406930291/this-is-the-font-used-in-fallout-1-2-its

Which ttf files are recommended? The ones in root or in release/?

I'm guessing it's impossible to have a font that preserves the actual bitmap-style antialiasing. But if you're interested and up to the challenge, perhaps a half-tone effect could be used? https://forum.glyphsapp.com/t/transparency-in-fonts/3214

**Comment by Sasabmeg** [comment]
Low resolution/size=10 + Only Latin Alphabet !!!
[Fallout-Classic-Dialog-Bold.ttf](https://github.com/Sasabmeg/fallout-classic-dialog-font/blob/main/release/Fallout-Classic-Dialog-Bold.ttf)

Otherwise, for higher pixels/easier on the eyes but still falloutish, most European and Cyrillic language support: [Fallout-Classic-Dialog-Regular.ttf](https://github.com/Sasabmeg/fallout-classic-dialog-font/blob/main/release/Fallout-Classic-Dialog-Regular.ttf)

Hi Ghost. So the thing is, that I'm not really a font creator, but one in need, so I have no professional awareness of what you suggest regarding font. I might look into it in the future, but atm preoccupied with more coding related matters on Fallout front ;)

I did describe it in fodev.net forum posts I believe, that the font like the original is the bold font file, but that hurts my eyes on bigger resolution, so I changed to a semi bold looking type, that still resembles Fallout dialog but more relaxing to read longer quests. Also, since due to this being an immense time sink for me, I did not complete all glyphs for the Bold style, so it only has Basic Latin character set only.

**Comment by ghostlyghastly** [comment]
Thanks for clarifying and best of success with the coding project(s)! For my current needs the font you provided here was perfect.

If I reaaaally need the anti aliased font one day I'll probably just try to make a little script that converts text into a montage of bitmaps. :D

**Comment by Sasabmeg** [comment]
https://github.com/Sasabmeg/foclassic-font-converter/blob/main/release/differences_regular_bold.png

This is how it looks on different resolutions loaded into FOClassic

**Comment by ghostlyghastly** [comment]
Very cool comparison pic!

By the way, having spotted your 6 years old 3d model project here on github, you might dig this: https://jonasz-o.itch.io/fallout2remake3d
